version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  cc_processor:
    image: cc_processor:latest  # Replace with your actual image name
    container_name: cc_processor
    ports:
      - "8080:80"  # Map port 80 in the container to port 8080 on the host
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  postgres_data:
