# Generated by Django 5.2.1 on 2025-06-15 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Phospho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.CharField(max_length=255)),
                ('phosphosite', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('proteome_file', models.CharField(max_length=255)),
                ('phosphoproteome_file', models.CharField(max_length=255)),
                ('proteome_file_accession_number_column_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PhosphoReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.FloatField(blank=True, null=True)),
                ('column_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phospho_reading', to='process.columnname')),
                ('phospho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phospho_reading', to='process.phospho')),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=255)),
                ('is_contaminant', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein', to='process.project')),
            ],
        ),
        migrations.AddField(
            model_name='phospho',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phospho', to='process.protein'),
        ),
        migrations.CreateModel(
            name='ProteinReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.FloatField(blank=True, null=True)),
                ('column_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_readings', to='process.columnname')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_readings', to='process.protein')),
            ],
        ),
        migrations.CreateModel(
            name='Replicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replicates', to='process.project')),
            ],
        ),
        migrations.AddField(
            model_name='columnname',
            name='replicate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_stages', to='process.replicate'),
        ),
        migrations.CreateModel(
            name='SampleStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_stages', to='process.project')),
            ],
        ),
        migrations.AddField(
            model_name='columnname',
            name='sample_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_names', to='process.samplestage'),
        ),
    ]
