# Generated by Django 5.2.1 on 2025-05-31 15:36

from django.db import migrations

from process.constants import (
    PHOSPHO_READINGS,
    PROTEIN_MEDIAN,
    PHOSPHO_MEDIAN,

    ZERO_MAX,
    LOG2_MEAN,
    PROTEIN_ABUNDANCES_RAW,
    PROTEIN_ABUNDANCES_IMPUTED,

    PROTEIN_ABUNDANCES_NORMALISED_ZERO_MAX,
    PROTEIN_ABUNDANCES_NORMALISED_MEDIAN,
    PROTEIN_ABUNDANCES_NORMALISED_MIN_MAX,
    PROTEIN_ABUNDANCES_NORMALISED_LOG2_MEAN,
    PROTEIN_ABUNDANCES_NORMALISED_LOG2_ARREST,

    PHOSPHO_REGRESSION_ZERO_MAX,
    PHOSPHO_REGRESSION_LOG2_MEAN,
    PHOSPHO_REGRESSION_POSITION_ABUNDANCES_RAW,
    PHOSPHO_REGRESSION_POSITION_ABUNDANCES_IMPUTED,
    PHOSPHO_REGRESSION_POSITION_ABUNDANCES_NORMALISED_ZERO_MAX,
    PHOSPHO_REGRESSION_POSITION_ABUNDANCES_NORMALISED_MEDIAN,
    PHOSPHO_REGRESSION_POSITION_ABUNDANCES_NORMALISED_MIN_MAX,
    PHOSPHO_REGRESSION_POSITION_ABUNDANCES_NORMALISED_LOG2_MEAN,
    PHOSPHO_REGRESSION_POSITION_ABUNDANCES_NORMALISED_LOG2_ARREST,

    PROTEIN_OSCILLATION_ABUNDANCES_ZERO_MAX,
    PROTEIN_OSCILLATION_ABUNDANCES_LOG2_MEAN,

    SL_SAMPLE_STAGE_NAME_1,
    SL_SAMPLE_STAGE_NAME_2,
    SL_SAMPLE_STAGE_NAME_3,
    SL_SAMPLE_STAGE_NAME_4,
    SL_SAMPLE_STAGE_NAME_5,
    SL_SAMPLE_STAGE_NAME_6,
    SL_SAMPLE_STAGE_NAME_7,
    SL_SAMPLE_STAGE_NAME_8,
    SL_SAMPLE_STAGE_NAME_9,
    SL_SAMPLE_STAGE_NAME_10
)


class Migration(migrations.Migration):
    def add_initial_data(apps, schema_editor):
        Project = apps.get_model("process", "Project")
        proj = Project.objects.create(
            name="SL",
            proteome_file="Soliman/results-request-2023MK001-proteome.xlsx",
            phosphoproteome_file="Soliman/results-request-2023MK004-phosphoproteome.xlsx",
            proteome_file_accession_number_column_name="Protein.Group",
        )

        Replicate = apps.get_model("process", "Replicate")
        replicate_1 = Replicate.objects.create(name="One", project=proj, mean=False)
        replicate_2 = Replicate.objects.create(name="Two", project=proj, mean=False)
        replicate_3 = Replicate.objects.create(name="Three", project=proj, mean=False)
        replicate_3 = Replicate.objects.create(name="Mean", project=proj, mean=True)

        SampleStage = apps.get_model("process", "SampleStage")
        sample_stage_1 = SampleStage.objects.create(
            project=proj, name=SL_SAMPLE_STAGE_NAME_1, rank=1
        )
        sample_stage_2 = SampleStage.objects.create(
            project=proj, name=SL_SAMPLE_STAGE_NAME_2, rank=2
        )
        sample_stage_3 = SampleStage.objects.create(
            project=proj, name=SL_SAMPLE_STAGE_NAME_3, rank=3
        )
        sample_stage_4 = SampleStage.objects.create(
            project=proj, name=SL_SAMPLE_STAGE_NAME_4, rank=4
        )
        sample_stage_5 = SampleStage.objects.create(
            project=proj, name=SL_SAMPLE_STAGE_NAME_5, rank=5
        )
        sample_stage_6 = SampleStage.objects.create(
            project=proj, name=SL_SAMPLE_STAGE_NAME_6, rank=6
        )
        sample_stage_7 = SampleStage.objects.create(
            project=proj, name=SL_SAMPLE_STAGE_NAME_7, rank=7
        )
        sample_stage_8 = SampleStage.objects.create(
            project=proj, name=SL_SAMPLE_STAGE_NAME_8, rank=8
        )
        sample_stage_9 = SampleStage.objects.create(
            project=proj, name=SL_SAMPLE_STAGE_NAME_9, rank=9
        )
        sample_stage_10 = SampleStage.objects.create(
            project=proj, name=SL_SAMPLE_STAGE_NAME_10, rank=10
        )

        ColumnName = apps.get_model("process", "ColumnName")
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_1,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_001_01_1ug.51b7a776fbe207cca4dc3cbaf3e65725.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_2,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_002_01_1ug.a972822c12d3531250fe20ae6ecb69aa.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_3,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_003_01_1ug.cad9400d7eba72576923cc895f70af6f.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_4,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_004_01_1ug.2ddb48073d9de37c4b0577bf07ec287e.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_5,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_005_01_1ug.d328d37a46090c888c870306d0667ee0.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_6,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_006_01_1ug.8742a276a5a238c3619d330452615790.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_7,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_007_01_1ug.9f20f2a13f46094c6e05d450368ac4b9.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_8,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_008_01_1ug.88c053097fe9088c531abea2e67c6758.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_9,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_009_01_1ug.7cc37d682de27eda4edef0ccab026af7.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_10,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_010_01_1ug.1c2b1a3ce2fa1ccbc6b7eac9ce05956d.mzML",
        )

        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_1,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_011_01_1ug.d0c28c029ee2c2e6db5b1b50665d4e4a.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_2,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_012_01_1ug.2a322473a6c3f2f17ef9d4a53ed71dcb.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_3,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_013_01_1ug.8b2322fec72c6dfc64e48985b201be31.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_4,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_014_01_1ug.d34730570aa7065d1b8fc1bf7c63120b.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_5,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_015_01_1ug.e1db3e62958d4004120df6232d7e4cfb.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_6,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_016_01_1ug.da2aa3f688849ccaf9b48f20c280feb7.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_7,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_017_01_1ug.224040fdec92fe339478bf8880fbdca4.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_8,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_018_01_1ug.0a587479bed4bb6ca2646b9fd4696929.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_9,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_019_01_1ug.e58220209d4d4a8ad4b75290b1afe11c.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_10,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_020_01_1ug.919455044bdeaaf3a82baf91dd9454fe.mzML",
        )

        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_1,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_021_01_1ug.e5a263c0704ca7f2c5ef59f622683b94.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_2,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_022_01_1ug.94bd6f3a75657b35542bcb0eb17bef0d.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_3,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_023_01_1ug.02320fcf5845af144f62809601a6c6ba.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_4,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_024_01_1ug.d86dfb6cbe421d43a505d2d564d3c6f7.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_5,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_025_01_1ug.4335cd91e3ccbe88508c7a9659b6c117.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_6,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_026_01_1ug.80960811cdc975851244195926b02747.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_7,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_027_01_1ug.5d7c208e6ec913f11208ca0af6e9a6a6.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_8,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_028_01_1ug.93de991e7437ba5b76cf9f6046801c9b.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_9,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_029_01_1ug.876cc9b4e0c16ec665ea03d6d1c3393c.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_10,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_030_01_1ug.90f58effdd53b09a52b544e757179640.mzML",
        )

        # Config for Institute of Cancer Research project
        project_ICR = Project.objects.create(
            name="ICR",
            proteome_file="ICR/CR07_TMT16plex_FullProt_Proteins.xlsx",
            phosphoproteome_file="ICR/20210610_CR07_IMAC_PeptideGroups.tdt",
            proteome_file_accession_number_column_name="Accession",
        )

        replicate_ICR_1 = Replicate.objects.create(
            name="abundance_rep_1", project=project_ICR, mean=False
        )
        replicate_ICR_2 = Replicate.objects.create(
            name="abundance_rep_2", project=project_ICR, mean=False
        )
        replicate_ICR_3 = Replicate.objects.create(
            name="abundance_average", project=project_ICR, mean=True
        )

        sample_stage_ICR_1 = SampleStage.objects.create(
            project=project_ICR, name="Palbo", rank=1
        )
        sample_stage_ICR_2 = SampleStage.objects.create(
            project=project_ICR, name="Late G1_1", rank=2
        )
        sample_stage_ICR_3 = SampleStage.objects.create(
            project=project_ICR, name="G1/S", rank=3
        )
        sample_stage_ICR_4 = SampleStage.objects.create(
            project=project_ICR, name="S", rank=4
        )
        sample_stage_ICR_5 = SampleStage.objects.create(
            project=project_ICR, name="S/G2", rank=5
        )
        sample_stage_ICR_6 = SampleStage.objects.create(
            project=project_ICR, name="G2_2", rank=6
        )
        sample_stage_ICR_7 = SampleStage.objects.create(
            project=project_ICR, name="G2/M_1", rank=7
        )
        sample_stage_ICR_8 = SampleStage.objects.create(
            project=project_ICR, name="M/Early G1", rank=8
        )

        ColumnName.objects.create(
            replicate=replicate_ICR_1,
            sample_stage=sample_stage_ICR_1,
            name="Abundance: 126, 1, 0",
        )
        ColumnName.objects.create(
            replicate=replicate_ICR_1,
            sample_stage=sample_stage_ICR_2,
            name="Abundance: 127N, 1, 2",
        )
        ColumnName.objects.create(
            replicate=replicate_ICR_1,
            sample_stage=sample_stage_ICR_3,
            name="Abundance: 127C, 1, 4",
        )
        ColumnName.objects.create(
            replicate=replicate_ICR_1,
            sample_stage=sample_stage_ICR_4,
            name="Abundance: 128N, 1, 6",
        )
        ColumnName.objects.create(
            replicate=replicate_ICR_1,
            sample_stage=sample_stage_ICR_5,
            name="Abundance: 128C, 1, 8",
        )
        ColumnName.objects.create(
            replicate=replicate_ICR_1,
            sample_stage=sample_stage_ICR_6,
            name="Abundance: 129N, 1, 10",
        )
        ColumnName.objects.create(
            replicate=replicate_ICR_1,
            sample_stage=sample_stage_ICR_7,
            name="Abundance: 129C, 1, 12",
        )
        ColumnName.objects.create(
            replicate=replicate_ICR_1,
            sample_stage=sample_stage_ICR_8,
            name="Abundance: 130N, 1, 15",
        )

        ColumnName.objects.create(
            replicate=replicate_ICR_2,
            sample_stage=sample_stage_ICR_1,
            name="Abundance: 130C, 2, 0",
        )
        ColumnName.objects.create(
            replicate=replicate_ICR_2,
            sample_stage=sample_stage_ICR_2,
            name="Abundance: 131N, 2, 2",
        )
        ColumnName.objects.create(
            replicate=replicate_ICR_2,
            sample_stage=sample_stage_ICR_3,
            name="Abundance: 131C, 2, 4",
        )
        ColumnName.objects.create(
            replicate=replicate_ICR_2,
            sample_stage=sample_stage_ICR_4,
            name="Abundance: 132N, 2, 6",
        )
        ColumnName.objects.create(
            replicate=replicate_ICR_2,
            sample_stage=sample_stage_ICR_5,
            name="Abundance: 132C, 2, 8",
        )
        ColumnName.objects.create(
            replicate=replicate_ICR_2,
            sample_stage=sample_stage_ICR_6,
            name="Abundance: 133N, 2, 10",
        )
        ColumnName.objects.create(
            replicate=replicate_ICR_2,
            sample_stage=sample_stage_ICR_7,
            name="Abundance: 133C, 2, 12",
        )
        ColumnName.objects.create(
            replicate=replicate_ICR_2,
            sample_stage=sample_stage_ICR_8,
            name="Abundance: 134N, 2, 15",
        )




        # Config for importing ICR results
        project_original = Project.objects.create(
            name="Original",
            proteome_file="N/A",
            phosphoproteome_file="N/A",
            proteome_file_accession_number_column_name="N/A",
        )

        replicate_original_1 = Replicate.objects.create(
            name="abundance_rep_1", project=project_original, mean=False
        )
        replicate_original_2 = Replicate.objects.create(
            name="abundance_rep_2", project=project_original, mean=False
        )
        replicate_original_3 = Replicate.objects.create(
            name="abundance_average", project=project_original, mean=True
        )

        sample_stage_original_1 = SampleStage.objects.create(
            project=project_original, name="Palbo", rank=1
        )
        sample_stage_original_2 = SampleStage.objects.create(
            project=project_original, name="Late G1_1", rank=2
        )
        sample_stage_original_3 = SampleStage.objects.create(
            project=project_original, name="G1/S", rank=3
        )
        sample_stage_original_4 = SampleStage.objects.create(
            project=project_original, name="S", rank=4
        )
        sample_stage_original_5 = SampleStage.objects.create(
            project=project_original, name="S/G2", rank=5
        )
        sample_stage_original_6 = SampleStage.objects.create(
            project=project_original, name="G2_2", rank=6
        )
        sample_stage_original_7 = SampleStage.objects.create(
            project=project_original, name="G2/M_1", rank=7
        )
        sample_stage_original_8 = SampleStage.objects.create(
            project=project_original, name="M/Early G1", rank=8
        )






        StatisticType = apps.get_model("process", "StatisticType")

        StatisticType.objects.create(
            name=PHOSPHO_READINGS,
        )
        StatisticType.objects.create(
            name=PROTEIN_MEDIAN,
        )
        StatisticType.objects.create(
            name=PHOSPHO_MEDIAN,
        )

        StatisticType.objects.create(
            name=ZERO_MAX,
        )
        StatisticType.objects.create(
            name=LOG2_MEAN,
        )

        StatisticType.objects.create(
            name=PROTEIN_ABUNDANCES_RAW,
        )
        StatisticType.objects.create(
            name=PROTEIN_ABUNDANCES_IMPUTED,
        )

        StatisticType.objects.create(
            name=PROTEIN_ABUNDANCES_NORMALISED_ZERO_MAX,
        )
        StatisticType.objects.create(
            name=PROTEIN_ABUNDANCES_NORMALISED_MEDIAN,
        )
        StatisticType.objects.create(
            name=PROTEIN_ABUNDANCES_NORMALISED_MIN_MAX,
        )
        StatisticType.objects.create(
            name=PROTEIN_ABUNDANCES_NORMALISED_LOG2_MEAN,
        )
        StatisticType.objects.create(
            name=PROTEIN_ABUNDANCES_NORMALISED_LOG2_ARREST,
        )

        StatisticType.objects.create(
            name=PHOSPHO_REGRESSION_ZERO_MAX,
        )
        StatisticType.objects.create(
            name=PHOSPHO_REGRESSION_LOG2_MEAN,
        )
        StatisticType.objects.create(
            name=PHOSPHO_REGRESSION_POSITION_ABUNDANCES_RAW,
        )
        StatisticType.objects.create(
            name=PHOSPHO_REGRESSION_POSITION_ABUNDANCES_IMPUTED,
        )
        StatisticType.objects.create(
            name=PHOSPHO_REGRESSION_POSITION_ABUNDANCES_NORMALISED_ZERO_MAX,
        )
        StatisticType.objects.create(
            name=PHOSPHO_REGRESSION_POSITION_ABUNDANCES_NORMALISED_MEDIAN,
        )
        StatisticType.objects.create(
            name=PHOSPHO_REGRESSION_POSITION_ABUNDANCES_NORMALISED_MIN_MAX,
        )
        StatisticType.objects.create(
            name=PHOSPHO_REGRESSION_POSITION_ABUNDANCES_NORMALISED_LOG2_MEAN,
        )
        StatisticType.objects.create(
            name=PHOSPHO_REGRESSION_POSITION_ABUNDANCES_NORMALISED_LOG2_ARREST,
        )

        StatisticType.objects.create(
            name=PROTEIN_OSCILLATION_ABUNDANCES_ZERO_MAX,
        )
        StatisticType.objects.create(
            name=PROTEIN_OSCILLATION_ABUNDANCES_LOG2_MEAN,
        )

    dependencies = [
        ("process", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
