# Generated by Django 5.2.1 on 2025-05-31 15:36

from django.db import migrations


class Migration(migrations.Migration):
    def add_initial_data(apps, schema_editor):
        Project = apps.get_model("process", "Project")
        proj = Project.objects.create(
            name="Soliman Labs",
            proteome_file="Soliman/results-request-2023MK001-proteome.xlsx",
            phosphoproteome_file="Soliman/results-request-2023MK004-phosphoproteome.xlsx",
        )

        Replicate = apps.get_model("process", "Replicate")
        replicate_1 = Replicate.objects.create(name="One", rank=1, project=proj)
        replicate_2 = Replicate.objects.create(name="Two", rank=2, project=proj)
        replicate_3 = Replicate.objects.create(name="Three", rank=3, project=proj)

        SampleStage = apps.get_model("process", "SampleStage")
        sample_stage_1 = SampleStage.objects.create(
            project=proj, name="RO sample 15 min", rank=1
        )
        sample_stage_2 = SampleStage.objects.create(
            project=proj, name="RO sample 30 min", rank=2
        )
        sample_stage_3 = SampleStage.objects.create(
            project=proj, name="Palb sample 1h", rank=3
        )
        sample_stage_4 = SampleStage.objects.create(
            project=proj, name="RO sample 2h", rank=4
        )
        sample_stage_5 = SampleStage.objects.create(
            project=proj, name="Palb sample, 2,5h", rank=5
        )
        sample_stage_6 = SampleStage.objects.create(
            project=proj, name="Palb sample, 4h", rank=6
        )
        sample_stage_7 = SampleStage.objects.create(
            project=proj, name="RO sample 5h", rank=7
        )
        sample_stage_8 = SampleStage.objects.create(
            project=proj, name="Palb sample, 8h", rank=8
        )
        sample_stage_9 = SampleStage.objects.create(
            project=proj, name="Palb sample, 10h", rank=9
        )
        sample_stage_10 = SampleStage.objects.create(
            project=proj, name="Nocodozole", rank=10
        )

        ColumnName = apps.get_model("process", "ColumnName")
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_1,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_001_01_1ug.51b7a776fbe207cca4dc3cbaf3e65725.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_2,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_002_01_1ug.a972822c12d3531250fe20ae6ecb69aa.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_3,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_003_01_1ug.cad9400d7eba72576923cc895f70af6f.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_4,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_004_01_1ug.2ddb48073d9de37c4b0577bf07ec287e.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_5,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_005_01_1ug.d328d37a46090c888c870306d0667ee0.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_6,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_006_01_1ug.8742a276a5a238c3619d330452615790.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_7,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_007_01_1ug.9f20f2a13f46094c6e05d450368ac4b9.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_8,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_008_01_1ug.88c053097fe9088c531abea2e67c6758.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_9,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_009_01_1ug.7cc37d682de27eda4edef0ccab026af7.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_1,
            sample_stage=sample_stage_10,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_010_01_1ug.1c2b1a3ce2fa1ccbc6b7eac9ce05956d.mzML",
        )

        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_1,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_011_01_1ug.d0c28c029ee2c2e6db5b1b50665d4e4a.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_2,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_012_01_1ug.2a322473a6c3f2f17ef9d4a53ed71dcb.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_3,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_013_01_1ug.8b2322fec72c6dfc64e48985b201be31.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_4,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_014_01_1ug.d34730570aa7065d1b8fc1bf7c63120b.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_5,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_015_01_1ug.e1db3e62958d4004120df6232d7e4cfb.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_6,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_016_01_1ug.da2aa3f688849ccaf9b48f20c280feb7.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_7,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_017_01_1ug.224040fdec92fe339478bf8880fbdca4.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_8,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_018_01_1ug.0a587479bed4bb6ca2646b9fd4696929.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_9,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_019_01_1ug.e58220209d4d4a8ad4b75290b1afe11c.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_2,
            sample_stage=sample_stage_10,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_020_01_1ug.919455044bdeaaf3a82baf91dd9454fe.mzML",
        )

        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_1,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_021_01_1ug.e5a263c0704ca7f2c5ef59f622683b94.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_2,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_022_01_1ug.94bd6f3a75657b35542bcb0eb17bef0d.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_3,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_023_01_1ug.02320fcf5845af144f62809601a6c6ba.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_4,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_024_01_1ug.d86dfb6cbe421d43a505d2d564d3c6f7.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_5,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_025_01_1ug.4335cd91e3ccbe88508c7a9659b6c117.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_6,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_026_01_1ug.80960811cdc975851244195926b02747.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_7,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_027_01_1ug.5d7c208e6ec913f11208ca0af6e9a6a6.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_8,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_028_01_1ug.93de991e7437ba5b76cf9f6046801c9b.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_9,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_029_01_1ug.876cc9b4e0c16ec665ea03d6d1c3393c.mzML",
        )
        ColumnName.objects.create(
            replicate=replicate_3,
            sample_stage=sample_stage_10,
            name="/users/pr/rawstream/2023MK001/mzml/2023MK001_IITI_030_01_1ug.90f58effdd53b09a52b544e757179640.mzML",
        )

    dependencies = [
        ("process", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
