# Generated by Django 5.2.1 on 2025-07-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0002_auto_20250708_1155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phospho",
            name="phosphosite",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
