# Generated by Django 5.2.1 on 2025-07-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20250730_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='phospho_pca',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='protein_pca',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
