# Generated by Django 5.2.1 on 2025-07-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20250708_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='gene_name',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='protein_name',
        ),
        migrations.CreateModel(
            name='GenomeOntologyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=255)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('accession_number',), name='unique_genome_ontology_data_accession_number')],
            },
        ),
        migrations.CreateModel(
            name='UniprotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=255)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('accession_number',), name='unique_uniprot_data_accession_number')],
            },
        ),
    ]
