# Generated by Django 5.2.1 on 2025-06-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20250615_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_proteins', models.BooleanField(default=False)),
                ('with_bugs', models.BooleanField(default=False)),
                ('protein_medians', models.JSONField(blank=True, null=True)),
                ('phospho_medians', models.JSONField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run', to='process.project')),
            ],
        ),
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_result', models.JSONField(blank=True, null=True)),
                ('phospho_result', models.JSONField(blank=True, null=True)),
                ('protein_phospho_result', models.JSONField(blank=True, null=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_result', to='process.protein')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_result', to='process.run')),
            ],
        ),
    ]
