# Generated by Django 5.2.1 on 2025-07-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_remove_protein_gene_name_remove_protein_protein_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='protein_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
