# Generated by Django 5.2.1 on 2025-07-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_project_protein_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='phospho_protein_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
