# Generated by Django 5.2.1 on 2025-07-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_project_phospho_protein_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='phospho_protein_GO_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='processable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='protein_GO_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
