# Generated by Django 5.2.1 on 2025-07-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_project_phospho_protein_go_list_project_processable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='phospho_protein_GO_list',
            new_name='phospho_protein_go_list',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='protein_GO_list',
            new_name='protein_go_list',
        ),
    ]
