# Generated by Django 5.2.1 on 2025-07-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_rename_phospho_protein_go_list_project_phospho_protein_go_list_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenomeOntologyData',
        ),
        migrations.RemoveField(
            model_name='project',
            name='phospho_protein_go_list',
        ),
    ]
