# Generated by Django 5.2.1 on 2025-07-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_delete_genomeontologydata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='phospho_protein_go_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
